### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Tatianka-hk** [Tatianka-hk/Dopk#3]
сделать аналог https://dns.google/

человек вводит домен
человек выбирает тип записи
человек нажимает получить информацию
происходит запрос на бекенд
на бекенде делается DNS запрос
результат отдается на фронтенда
результат визуализируется
человек может шорткатами перемещаться между типами записей в рамках домена
Приемка: обработка сложных кейсов, вроде несуществующих записей либо записей со списками ip блоков (которые могут быть огромными) и проверка что они не сломаются в визуальном представлении

URL должен отражать стейт приложения, то есть если человек выбрал - я хочу увидеть A записи домена google.com то это должно быть отражено в урл, чтобы скопировав его и передав другому пользователю можно было повторить состояние.

**Comment by nosovk** [comment]
URL должен отражать стейт приложения, то есть если человек выбрал - я хочу увидеть A записи домена google.com то это должно быть отражено в урл, чтобы скопировав его и передав другому пользователю можно было повторить состояние.

Техническая реализация этого поведения сделать через writeableStore - https://svelte.dev/tutorial/writable-stores

**Comment by nosovk** [comment]
А как же слить PR?
